[project]
name = "torchattack"
description = "A set of adversarial attacks implemented in PyTorch"
authors = [{ name = "spencerwooo", email = "spencer.woo@outlook.com" }]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = { text = "MIT" }
dependencies = [
    "torch>=1.13.0",
    "torchvision>=0.14.0",
    "numpy>=1.24.2",
    "scipy>=1.10.1",
]
dynamic = ["version"]
optional-dependencies = { dev = ["mypy", "rich", "timm"] }

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "torchattack.__version__" }

[tool.setuptools.packages.find]
include = ["torchattack"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "N", "B", "SIM"]
ignore = ["E501", "B905"]

[tool.ruff.format]
quote-style = "single"

[tool.mypy]
no_implicit_optional = true
check_untyped_defs = true
ignore_missing_imports = true # Used as torchvision does not ship type hints

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
# disallow_any_unimported = true
# disallow_untyped_defs = true
# warn_return_any = true
