name: lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Ruff format
        uses: chartboost/ruff-action@v1
        with:
          args: format --check

      - name: Ruff lint
        uses: chartboost/ruff-action@v1

      - name: Install uv
        run: |
          python -m pip install -U pip
          python -m pip install uv

      - name: Allow uv to use the system Python by default
        run: echo "UV_SYSTEM_PYTHON=1" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
          uv pip install -e '.[dev]'

      - name: Mypy
        run: |
          mypy torchattack
